development:
  adapter: mysql2
  encoding: utf8
  database: myapp_development
  username: root
  password: 'joog'
  host: 127.0.0.1
  port: 3306
test:
  adapter: mysql2
  encoding: utf8
  database: myapp_test
  username: root
  password: 'joog'
  host: 127.0.0.1
  port: 3306
production:
  adapter: postgresql
  encoding: unicode
  database: d29s7nq874o22t
  post: 5
  username: btzoqgefkrgtxb
  password: 75vXUa5xQkZFuXUmEHLxx5BoQa
  port: 5432
