# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 300823be95f6d03bf67cf92e54374b029bec1480261a3e06562c0ba4f518fc5be76d1164e81b553f014e018e7ef60ec4495d5d54622cd7856ae9b8fb544f63a6

test:
  secret_key_base: 593ac5cb374555e9b103fd557980dbe68a3c2ba076b13dbdc2ac4f8040abb6caea4101158dffa51e049e0b18f0cdb0c0e989f588ea3cdf8173562852a3537511

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
